### ISSUE TITLE
RRuleField

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/django_api_forms#19]
It will be nice to have RRuleField which will normalize from [RRULE](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html) to [dateutil.rrule](https://dateutil.readthedocs.io/en/stable/rrule.html) object.

Field should be available only if [dateutil](https://pypi.org/project/python-dateutil/) is installed (it's not required dependency).

**Comment by yopknopixx** [comment]
Hello, I'd like to work on this issue. @Sibyx Please let me know where to start.

**Comment by iamhardikat11** [comment]
I am a novice programmer with regards, to Django Programming in Python.  I would love to contribute to this Issue. Please Assign this Issue to Me.

**Comment by Sibyx** [comment]
Hi @iamhardikat11. Feel free to take the issue, implementation is quite simple. I have a few recommendations regarding to this issue:

## Notes

You suppose to implement a new Field class (for example `RRuleField`) in the [fields](https://github.com/Sibyx/django_api_forms/blob/master/django_api_forms/fields.py). Check the implementation of the existing ones to get familiar (all fields suppose to inherit from `Field` class). The purpose of the field is to consume an [rrule](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html) string and return [rrule](https://dateutil.readthedocs.io/en/stable/rrule.html) object from [dateutil](https://dateutil.readthedocs.io/en/stable/index.html) library. Please note that `dateutil` is not suppose to be an mandatory dependency. Check how are extras implemented in the [ImageField](https://github.com/Sibyx/django_api_forms/blob/master/django_api_forms/fields.py#L270) class.

## TODO

- [ ] Implement an `RRuleField`
- [ ] Write new unit tests (do not change old ones)
- [ ] Write docs
- [ ] Change `setup.py` and `pyproject.toml` (for extras)

**Comment by iamhardikat11** [comment]
Thanks @Jakub Dubec. Will work in accordance with the Provided Guidelines.
Thank You.

**Comment by iamhardikat11** [comment]
Sir, I have started working on the Issue and updated the Docs, can you help me know what exactly is a TOML File?

**Comment by iamhardikat11** [comment]
And what modifications do I have to Make in order to Complete this Issue?

**Comment by Sibyx** [comment]
Hello,

file `pyproject.toml` is file originaly specified in [PEP518](https://www.python.org/dev/peps/pep-0518/). Poetry and some other tools also use it to store it's configuration. 

It looks like I made a little mistake in defining the TODO list. You don't have to change `pyproject.toml` (I thought I already specified extras in the `pyproject,.toml`).  You just have to specify new extras in [EXTRAS dictionary](https://github.com/Sibyx/django_api_forms/blob/master/setup.py#L11) (let's say extras called `rrule` witch points to the `dateutil` dependency).

Feel free to create a PR, it simplifies the code-review process.

**Comment by iamhardikat11** [comment]
Awesome, thanks!

**Comment by Sibyx** [comment]
Hi @iamhardikat11,
how are you doing? Do you have any updates or thinks you need to help with?

**Comment by iamhardikat11** [comment]
Can you help me with resources to get onto RRule Field. Actually there's
Examination underway in my College Right Now. Sorry for the delay.
Thanks for your Cooperation.
Hardik Soni

**Comment by AmberAnsari89** [comment]
Hi,
i did few changes as below however i need more information on receiving input string and returning object type and also special validations on string.
[class RRuleField.docx](https://github.com/Sibyx/django_api_forms/files/9855204/class.RRuleField.docx)

**Comment by AmberAnsari89** [comment]
hi ,
can i start working on it?

**Comment by paimvictor** [comment]
Hey there!

I've created a pull request, let me know what changes could i make
#52
